// ============================================================
// APP STATE — Top-level client-side container (React Context)
// ============================================================

export interface AppState {
  currentScreen: ScreenName;
  createdAt: Date;

  // Source data (populated in S1)
  source: SourceData;

  // Oracle outputs (populated in S2, from /api/process-source response)
  oracle: OracleData | null;

  // Conversation state (populated during S3, managed client-side)
  conversation: ConversationData;

  // Grading results (populated in S4/S5, from /api/grade response)
  grading: GradingData | null;
}

export type ScreenName = 'upload' | 'topic' | 'teaching' | 'testing' | 'report';

// ============================================================
// SOURCE DATA — User's uploaded material
// ============================================================

export interface SourceData {
  sourceText: string;
  sourceType: 'pdf' | 'text';
  subtopic: string;
  fileName?: string;
  characterCount: number;
}

// ============================================================
// ORACLE DATA — Generated by Oracle Agent
// ============================================================

export interface OracleData {
  topicOutline: string[];
  testQuestions: TestQuestion[];
  answerKey: AnswerKeyEntry[];
  generatedAt: Date;
}

export interface TestQuestion {
  id: string;
  question: string;
}

export interface AnswerKeyEntry {
  questionId: string;
  expectedAnswer: string;
  keyConcepts: string[];
  sourceExcerpt: string;
}

// ============================================================
// CONVERSATION DATA — Teaching session state
// ============================================================

export interface ConversationData {
  messages: Message[];
  coveredSubtopics: string[];
  tuteeState: TuteeState;
  messageCount: number;
  startedAt: Date | null;
  endedAt: Date | null;
}

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  tuteeState?: TuteeState;
}

export type TuteeState = 'idle' | 'thinking' | 'confused' | 'test-taking';

// ============================================================
// GRADING DATA — Test results and report
// ============================================================

export interface GradingData {
  overallScore: number;
  totalQuestions: number;
  percentage: number;
  questionResults: QuestionResult[];
  tuteeTestAnswers: TuteeTestAnswer[];
  gradedAt: Date;
}

export interface QuestionResult {
  questionId: string;
  question: string;
  tuteeAnswer: string;
  expectedAnswer: string;
  isCorrect: boolean;
  gap?: string;
}

export interface TuteeTestAnswer {
  questionId: string;
  answer: string;
  confidence: 'high' | 'low' | 'none';
}

// ============================================================
// AGENT API RESPONSE TYPES
// ============================================================

// Oracle API response shape
export interface OracleOutput {
  topicOutline: string[];
  testQuestions: TestQuestion[];
  answerKey: AnswerKeyEntry[];
}

// Tutee API response shape
export interface TuteeResponse {
  message: string;
  state: TuteeState;
  coveredSubtopics: string[];
}

// Grading result shape (from grader)
export interface GradingResult {
  overallScore: number;
  totalQuestions: number;
  percentage: number;
  questionResults: QuestionResult[];
}
